name = "freeimagelab-worker"
main = "src/index.ts"
compatibility_date = "2025-05-11"

# Workaround for Worker-to-itself fetch 522 bug
compatibility_flags = ["no_minimal_subrequests"]

[site]
bucket = "./templates"          # 1. Upload this directory
entry-point = "workers-site"    # 2. Enable SPA fallback
