name = "freeimagelab-worker"
main = "src/index.ts"
compatibility_date = "2025-05-11"

[site]
bucket = "./templates"        # ← points to the folder above
entry-point = "workers-site"  # if using Wrangler’s default Sites template
exclude = ["**/.ipynb_checkpoints/**"]
